#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Copyright © 2015 Martin Ueding <dev@martin-ueding.de>

import argparse
import itertools
import pprint

import matplotlib.pyplot as pl
import numpy as np
import pandas as pd
import scipy.integrate
import scipy.ndimage.filters


colors = [
'#a6cee3',
'#1f78b4',
'#b2df8a',
'#33a02c',
'#fb9a99',
'#e31a1c',
'#fdbf6f',
'#ff7f00',
'#cab2d6',
'#6a3d9a',
'#b15928',
]

linestyles = [
    'solid',
    'dashed',
]

pp = pprint.PrettyPrinter()

def lorentz_peak(x, mean, width, area, offset):
    return area / np.pi * width/2 / ((x - mean)**2 + (width/2)**2) + offset

def load_lines():
    filename = 'Daten/generiesb.dat'
    data = pd.read_csv(filename, header=0, delim_whitespace=True)

    return data

def get_peaks():
    return np.loadtxt('Daten/Langzeit_Peaks.dat')

def main():
    options = _parse_args()

    messwerte = np.loadtxt('_build/langzeit.tsv')

    messwerte = messwerte[messwerte[:, 0] > 200]

    messwerte_smooth = scipy.ndimage.filters.gaussian_filter(messwerte[:, 1], 100)
    ohne_untergrund = messwerte[:, 1] - messwerte_smooth

    #print(messwerte.shape)

    peaks = get_peaks()

    lines = load_lines()

    pad = 2

    elements = list(set(lines['Nuclide']))
    #print(elements)

    fig = pl.figure()
    ax = fig.add_subplot(1, 1, 1)

    results = {}

    m = 0

    attr_iter = itertools.cycle(itertools.product(linestyles, colors))

    exclude = [
            '11-Na-22',
            '21-Sc-46',
            '25-Mn-54',
            '25-Mn-56',
            '27-Co-56',
            '27-Co-58',
            '27-Co-60',
            '30-Zn-65',
            '31-Ga-66',
            '36-Kr-85',
            '38-Sr-85',
            '41-Nb-95',
            '44-Ru-106',
            '45-Rh-106',
            '55-Cs-134',
            '67-Ho-166',
            '88-Ra-224',
    ]

    candidates = []

    for element in elements:
        if element in exclude:
            continue

        selection = lines['Nuclide'] == element
        selected = lines[selection]

        x = messwerte[:, 0]
        y = np.zeros(x.shape)

        for id, energy, delta_energy, sigma_val, sigma_err, nuclide in selected.itertuples():
            y += lorentz_peak(x, energy, 1.5, sigma_val, 0)


        self_integral = scipy.integrate.simps(y, x)
        overlap = y * ohne_untergrund
        overlap_integral = scipy.integrate.simps(overlap, x)

        score = overlap_integral / self_integral

        results[element] = score

        candidates.append((score, element, y / self_integral))

    for score, element, y in itertools.islice(reversed(sorted(candidates)), 22):
        linestyle, color = next(attr_iter)
        ax.plot(x, y, label=element, color=color, linestyle=linestyle, linewidth=2)
        m = max(m, np.max(y))

    ax.legend(loc='best')

    m2 = np.max(messwerte[:, 1])

    #print('m', m)
    #print('m2', m2)
    scale = ax.get_ylim()[1] / m2
    #print('Scale', scale)

    ax.plot(x, messwerte[:, 1] * scale, alpha=0.3, color='black')
    ax.plot(x, messwerte_smooth * scale, alpha=0.3, color='black')

    ax.grid(True)
    ax.margins(.05)
    fig.tight_layout()

    if options.show:
        fig.show()
        input()
    else:
        fig.savefig('_build/element_match.pdf')

    results_sorted = sorted([(matchness, element) for element, matchness in results.items()])

    # Zeige Matchness an

    for matchness, element in results_sorted:
       print('{:5s} {:+.10f}'.format(element, matchness))



def _parse_args():
    '''
    Parses the command line arguments.

    :return: Namespace with arguments.
    :rtype: Namespace
    '''
    parser = argparse.ArgumentParser(description='')
    parser.add_argument('--show', action='store_true')
    options = parser.parse_args()

    return options

if __name__ == '__main__':
    main()
